---
dist: "xenial"
language: "ruby"
cache: "bundler"
before_install:
  - "bundle -v"
  - "rm -f Gemfile.lock"
  - "gem update --system $RUBYGEMS_VERSION"
  - "gem --version"
  - "bundle -v"
script:
  - 'bundle exec rake $CHECK'
bundler_args: "--without system_tests"
rvm:
  - "2.5.3"
matrix:
  fast_finish: true
  include:
    - env: "CHECK='check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint'"
    - env: "TEST=yamllint"
      language: "minimal"
      services:
        - "docker"
      script: "./tests/yamllint.sh"

    - env: "TEST=markdownlint"
      language: "minimal"
      services:
        - "docker"
      script: "./tests/mdl.sh"

    - env: "TEST=shellcheck"
      language: "minimal"
      services:
        - "docker"
      script: "./tests/shellcheck.sh"
notifications:
  email: false
